services:
  - type: web
    name: firecrow
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: firecrow-db
          property: connectionString
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: firecrow-db
    databaseName: firecrow
    user: firecrow_user
