services:
  - type: web
    name: firecrow
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
