"""add_domain_verifications

Revision ID: 187c538a7649
Revises: 8f7e6d5c4b3a
Create Date: 2026-07-05 23:54:05.942463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '187c538a7649'
down_revision: Union[str, Sequence[str], None] = '8f7e6d5c4b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=512), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_verifications_domain'), 'domain_verifications', ['domain'], unique=False)
    op.create_index(op.f('ix_domain_verifications_tenant_id'), 'domain_verifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_domain_verifications_user_id'), 'domain_verifications', ['user_id'], unique=False)
    op.drop_column('audit_jobs', 'auto_push')
    op.drop_index(op.f('ix_users_email_lower_unique'), table_name='users', postgresql_where='(email IS NOT NULL)')
    op.drop_column('users', 'auto_email_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auto_email_reports', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_email_lower_unique'), 'users', [sa.literal_column('lower(email::text)')], unique=True, postgresql_where='(email IS NOT NULL)')
    op.add_column('audit_jobs', sa.Column('auto_push', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_domain_verifications_user_id'), table_name='domain_verifications')
    op.drop_index(op.f('ix_domain_verifications_tenant_id'), table_name='domain_verifications')
    op.drop_index(op.f('ix_domain_verifications_domain'), table_name='domain_verifications')
    op.drop_table('domain_verifications')
    # ### end Alembic commands ###
