"""add_missing_columns

Revision ID: ce1b119cf0fd
Revises: 5c8fab6ef775
Create Date: 2026-06-07 19:42:24.940248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'ce1b119cf0fd'
down_revision: Union[str, Sequence[str], None] = '5c8fab6ef775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(inspector, table_name: str) -> bool:
    return table_name in inspector.get_table_names()


def _column_exists(inspector, table_name: str, column_name: str) -> bool:
    return any(column["name"] == column_name for column in inspector.get_columns(table_name))


def _index_exists(inspector, table_name: str, index_name: str) -> bool:
    return any(index["name"] == index_name for index in inspector.get_indexes(table_name))


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)

    if not _table_exists(inspector, "audit_artifacts"):
        op.create_table(
            "audit_artifacts",
            sa.Column("id", sa.String(length=36), nullable=False),
            sa.Column("job_id", sa.String(length=36), nullable=False),
            sa.Column("artifact_type", sa.String(length=100), nullable=False),
            sa.Column("name", sa.String(length=255), nullable=False),
            sa.Column("data_json", sa.String(), nullable=True),
            sa.Column("data_text", sa.String(), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(["job_id"], ["audit_jobs.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        inspector = inspect(bind)
    if not _index_exists(inspector, "audit_artifacts", op.f("ix_audit_artifacts_job_id")):
        op.create_index(op.f("ix_audit_artifacts_job_id"), "audit_artifacts", ["job_id"], unique=False)

    finding_columns = {column["name"] for column in inspector.get_columns("findings")} if _table_exists(inspector, "findings") else set()
    if "confidence" not in finding_columns:
        op.add_column("findings", sa.Column("confidence", sa.String(length=50), nullable=True))
    if "scanner_name" not in finding_columns:
        op.add_column("findings", sa.Column("scanner_name", sa.String(length=100), nullable=True))
    if "scanner_mode" not in finding_columns:
        op.add_column("findings", sa.Column("scanner_mode", sa.String(length=50), nullable=True))
    if "file_path" not in finding_columns:
        op.add_column("findings", sa.Column("file_path", sa.String(length=1024), nullable=True))
    if "line_number" not in finding_columns:
        op.add_column("findings", sa.Column("line_number", sa.Integer(), nullable=True))
    if "route" not in finding_columns:
        op.add_column("findings", sa.Column("route", sa.String(length=1024), nullable=True))
    if "metadata_json" not in finding_columns:
        op.add_column("findings", sa.Column("metadata_json", sa.String(), nullable=True))

    user_columns = {column["name"] for column in inspector.get_columns("users")} if _table_exists(inspector, "users") else set()
    if "github_access_token" not in user_columns:
        op.add_column("users", sa.Column("github_access_token", sa.Text(), nullable=True))
    if "github_token_scopes" not in user_columns:
        op.add_column("users", sa.Column("github_token_scopes", sa.Text(), nullable=True))
    if "github_token_updated_at" not in user_columns:
        op.add_column("users", sa.Column("github_token_updated_at", sa.DateTime(timezone=True), nullable=True))
    if "terms_version" not in user_columns:
        op.add_column("users", sa.Column("terms_version", sa.String(length=64), nullable=True))
    if "terms_accepted_at" not in user_columns:
        op.add_column("users", sa.Column("terms_accepted_at", sa.DateTime(timezone=True), nullable=True))
    if "first_login_at" not in user_columns:
        op.add_column("users", sa.Column("first_login_at", sa.DateTime(timezone=True), nullable=True))
    if "last_login_at" not in user_columns:
        op.add_column("users", sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True))
    if "last_logout_at" not in user_columns:
        op.add_column("users", sa.Column("last_logout_at", sa.DateTime(timezone=True), nullable=True))
    if "activity_log" not in user_columns:
        op.add_column("users", sa.Column("activity_log", sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activity_log')
    op.drop_column('users', 'last_logout_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'first_login_at')
    op.drop_column('users', 'terms_accepted_at')
    op.drop_column('users', 'terms_version')
    op.drop_column('users', 'github_token_updated_at')
    op.drop_column('users', 'github_token_scopes')
    op.drop_column('users', 'github_access_token')
    op.drop_column('findings', 'metadata_json')
    op.drop_column('findings', 'route')
    op.drop_column('findings', 'line_number')
    op.drop_column('findings', 'file_path')
    op.drop_column('findings', 'scanner_mode')
    op.drop_column('findings', 'scanner_name')
    op.drop_column('findings', 'confidence')
    op.drop_index(op.f('ix_audit_artifacts_job_id'), table_name='audit_artifacts')
    op.drop_table('audit_artifacts')
    # ### end Alembic commands ###
