"""add_audit_reports

Revision ID: 3a3e549bf3a8
Revises: d8a7f2b0c1aa
Create Date: 2026-06-08 19:52:55.409325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3e549bf3a8'
down_revision: Union[str, Sequence[str], None] = 'd8a7f2b0c1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('html_content', sa.String(), nullable=True),
    sa.Column('markdown_content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['audit_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_reports_job_id'), 'audit_reports', ['job_id'], unique=False)
    op.add_column('audit_jobs', sa.Column('report_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_jobs', 'report_id')
    op.drop_index(op.f('ix_audit_reports_job_id'), table_name='audit_reports')
    op.drop_table('audit_reports')
    # ### end Alembic commands ###
