"""add auto_email_reports to user

Revision ID: b6431235eb7a
Revises: 5c8fab6ef775
Create Date: 2026-06-09 18:06:13.093410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6431235eb7a'
down_revision: Union[str, Sequence[str], None] = '5c8fab6ef775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auto_email_reports', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('github_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('github_token_scopes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('github_token_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('terms_version', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('first_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_logout_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('activity_log', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activity_log')
    op.drop_column('users', 'last_logout_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'first_login_at')
    op.drop_column('users', 'terms_accepted_at')
    op.drop_column('users', 'terms_version')
    op.drop_column('users', 'github_token_updated_at')
    op.drop_column('users', 'github_token_scopes')
    op.drop_column('users', 'github_access_token')
    op.drop_column('users', 'auto_email_reports')
    # ### end Alembic commands ###
