"""add_missing_columns

Revision ID: ce1b119cf0fd
Revises: 5c8fab6ef775
Create Date: 2026-06-07 19:42:24.940248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1b119cf0fd'
down_revision: Union[str, Sequence[str], None] = '5c8fab6ef775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_json', sa.String(), nullable=True),
    sa.Column('data_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['audit_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_artifacts_job_id'), 'audit_artifacts', ['job_id'], unique=False)
    op.add_column('findings', sa.Column('confidence', sa.String(length=50), nullable=True))
    op.add_column('findings', sa.Column('scanner_name', sa.String(length=100), nullable=True))
    op.add_column('findings', sa.Column('scanner_mode', sa.String(length=50), nullable=True))
    op.add_column('findings', sa.Column('file_path', sa.String(length=1024), nullable=True))
    op.add_column('findings', sa.Column('line_number', sa.Integer(), nullable=True))
    op.add_column('findings', sa.Column('route', sa.String(length=1024), nullable=True))
    op.add_column('findings', sa.Column('metadata_json', sa.String(), nullable=True))
    op.add_column('users', sa.Column('github_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('github_token_scopes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('github_token_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('terms_version', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('first_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_logout_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('activity_log', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activity_log')
    op.drop_column('users', 'last_logout_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'first_login_at')
    op.drop_column('users', 'terms_accepted_at')
    op.drop_column('users', 'terms_version')
    op.drop_column('users', 'github_token_updated_at')
    op.drop_column('users', 'github_token_scopes')
    op.drop_column('users', 'github_access_token')
    op.drop_column('findings', 'metadata_json')
    op.drop_column('findings', 'route')
    op.drop_column('findings', 'line_number')
    op.drop_column('findings', 'file_path')
    op.drop_column('findings', 'scanner_mode')
    op.drop_column('findings', 'scanner_name')
    op.drop_column('findings', 'confidence')
    op.drop_index(op.f('ix_audit_artifacts_job_id'), table_name='audit_artifacts')
    op.drop_table('audit_artifacts')
    # ### end Alembic commands ###
