export const privacySections = [
  {
    title: "How Nova Devs protects your code",
    body:
      "Fire Crow is built by Nova Devs with privacy as a core principle. We only scan repositories you explicitly authorize. We do not use your proprietary code to train machine learning models.",
  },
  {
    title: "What information we collect",
    body:
      "We only store the email address you use to sign in, authorization logs for scans you request, and the final security findings and reports. All data is kept securely in encrypted storage.",
  },
  {
    title: "Data deletion",
    body:
      "You have full control over your data. You can delete your security reports, scan history, or your entire account at any time. Deleted data is immediately and permanently removed from our active databases.",
  },
  {
    title: "Zero third-party sharing",
    body:
      "Nova Devs will never sell, trade, or share your repository contents or scan results with external advertising networks or unrelated third parties. Your code and security reports are strictly your own.",
  },
];

export const termsSections = [
  {
    title: "Explicit authorization required",
    body:
      "You may only scan repositories for which you have clear ownership or explicit permission to run security checks. Unauthorized testing is strictly prohibited.",
  },
  {
    title: "Use of security reports",
    body:
      "The findings and reports generated by Fire Crow are for your internal remediation and client compliance. Nova Devs provides these reports on an 'as-is' basis to help identify risks, but they do not constitute legal certification or a guarantee against future vulnerabilities.",
  },
  {
    title: "Account responsibility",
    body:
      "You are responsible for keeping your credentials safe and managing who has access to your workspace. Please notify Nova Devs immediately if you notice any unauthorized access.",
  },
  {
    title: "Updates to services",
    body:
      "Nova Devs reserves the right to improve, update, or temporarily pause features to perform maintenance or enhance scanner definitions. We will notify active users of any significant changes.",
  },
];
